### ISSUE TITLE
Log for orchestrator and nodes

### ISSUE THREAD

**Issue by ppuertocrem** [IntegrCiTy/obnl#1]
Is it possible to create a system of logs for the orchestrator as well as for for the nodes in order to see properly which node is connected which one did not manage to connect, etc. ?

**Comment by ppuertocrem** [comment]
Is it also possible to have a log from the orchestrator node that says "Simulation finished in X.X sec" at the end of the simulation ?

**Comment by gbasso** [comment]
It is possible to use the logger module to activate logging. On develop since: https://github.com/IntegrCiTy/obnl/commit/b03bbbf27388d1dbcaa883dc5bfad43570480508.
On master since 0.3.0.
