### ISSUE TITLE
ID of simulation run passed to ClientNode (MultipleDatabase name for Redis)

### ISSUE THREAD

**Issue by ppuertocrem** [IntegrCiTy/obnl#3]
Is it possible to pass an ID of simulation to ClientNode ?
The idea is to be able to give a name of the Redis DB to the nodes at init before simulation (in order to store different run).

**Comment by gbasso** [comment]
On develop : 921117b9388409b6bb1aadb3717fd14c073ee185
It is possible to access to a simulation ID after the connection of a Node to the orchestrator in the `simulation` property (before connection the value is `None`).
